#!/bin/bash

#Display if the user is root or not. the $UID variable is given to us by the os and we do not
#need to declare it. The -eq stanjds for equal. Root is user 0. The spacing between the brackets
#in the if statement is verry important and will not work without it. fi is needed to end all if statments "finish"

if [[ $UID -eq 0 ]]
then
  echo "You are the root user"
else
  echo "You are not the root user"
fi

#in linux we can use > < == != and everything else we would espect with a prgoramming language, but they also have 
#-eg -ne -lt -le -gt -ge


UID_TO_TEST_FOR='1000'

if [[ $UID -ne $UID_TO_TEST_FOR ]]
then
  echo "Your UID does not match $UID_TO_TEST_FOR"
else
  echo 'Your UID does match!'
fi

# Grab username
USER_NAME=$(id -un)

# Define a username to test for.
USER_NAME_TO_TEST_FOR='russell'
if [[ $USER_NAME_TO_TEST_FOR -eq $USER_NAME ]]
then
  echo "Your username matches $USER_NAME_TO_TEST_FOR"
exit 1
fi
  echo 'Your username is $USER_NAME'
#the last line of the script should always be exit 0
exit 0
